### ISSUE TITLE
Url linked from GitHub repo is 404

### ISSUE THREAD

**Issue by mithro** [edaa-org/pyEDAA.ProjectModel#32]
The link https://edaa-org.github.io/pyEDAA.ProjectModel/ ends up at a 404.

**Comment by Paebbels** [comment]
@umarcor is this because several pipelines failed and the website was going to be replaces with a new version but failed?

**Comment by umarcor** [comment]
@mithro, for some reason we are uploading the documentation to https://edaa-org.github.io/pyEDAA.ProjectModel/documentation/. That last `documentation` subdir should not be there. Let me have a look. Both @Paebbels and me have been reworking the CI and it seems we changed that unwantedly.

**Comment by umarcor** [comment]
@Paebbels, see https://github.com/edaa-org/pyEDAA.ProjectModel/tree/gh-pages.

**Comment by umarcor** [comment]
It's fixed now:

- Main documentation: https://edaa-org.github.io/pyEDAA.ProjectModel/
- Coverage report: https://edaa-org.github.io/pyEDAA.ProjectModel/coverage/index.html
- Static Type Checking Report: https://edaa-org.github.io/pyEDAA.ProjectModel/typing/index.html
