### ISSUE TITLE
Setup Codacy when going public

### ISSUE THREAD

**Issue by umarcor** [edaa-org/pyEDAA.ProjectModel#5]
When going public, we need to exchange this ID with the correct project ID and also setup a secret for codacy (as well as a publishing token for PyPI).

*Originally posted by @Paeebels in https://github.com/edaa-org/pyEDAA.ProjectModel/pull/3#pullrequestreview-764982198*

**Comment by Paebbels** [comment]
The secret is configured for pushing results and the changed IDs for badges will be integrated via #11.
