### ISSUE TITLE
How can I add a FileSet to a FileSet?

### ISSUE THREAD

**Issue by RasmusGOlsen** [edaa-org/pyEDAA.ProjectModel#52]
It seems like the `FileSet` class is missing a function to add a `FileSet` to the private variable `_fileSets`. Furthermore, what is the thought behind declaring `_fileSets` as a `dict` and not a `list`?

**Comment by Paebbels** [comment]
Oh you're right. A file and a sequence of files can be added, but no fileset.

I'll fix that. It's a bug.

------------
Fileset have names. The dictionary is to lookup a sub-filesets by name.

**Comment by Paebbels** [comment]
There will be:
* `fileSet.AddFileSet(subFileSet)`
* `fileSet.AddFileSets(subFileSets)`

Anything else missing like that?

-------
As a temporary workaround, there is currently the other way around:
* `subFileSet.Parent = fileSet`
